import importlib
import inspect
import glob
import os
import sys
import traceback
import time
import shutil
import matplotlib.pyplot as plt

sys.path.append(os.path.abspath(os.path.dirname(__file__)))
from style_manager import apply_academic_style, apply_commercial_style

def main():
    plot_files = glob.glob("plot_*.py")
    plot_files = [f for f in plot_files if os.path.basename(f) != "plot_template.py"]
    plot_files.sort()

    output_base = "output_templates"
    os.makedirs(output_base, exist_ok=True)
    original_savefig = plt.savefig

    for file in plot_files:
        module_name = os.path.basename(file)[:-3]
        try:
            module = importlib.import_module(module_name)
            print(f"--- Processing {module_name} ---")
            
            functions = []
            for name, obj in inspect.getmembers(module, inspect.isfunction):
                if obj.__module__ == module_name:
                    if name.startswith('plot_') or name.startswith('create_'):
                        functions.append((name, obj))
            
            for name, func in functions:
                sig = inspect.signature(func)
                can_call = True
                for param_name, param in sig.parameters.items():
                    if param_name not in ['style', 'style_name', 'output_path']:
                        if param.default == inspect.Parameter.empty:
                            can_call = False
                            break
                
                if not can_call:
                    continue
                
                for i in range(10):
                    timestamp = int(time.time() * 1000)
                    out_dir = os.path.join(output_base, f"{name}_{timestamp}_{i}")
                    os.makedirs(out_dir, exist_ok=True)
                    
                    # academic
                    try:
                        print(f"  Executing {name} (academic) iteration {i+1}/10...")
                        apply_academic_style()
                        kwargs = {}
                        if 'style' in sig.parameters:
                            kwargs['style'] = 'academic'
                        elif 'style_name' in sig.parameters:
                            kwargs['style_name'] = 'academic'
                            
                        academic_out = os.path.join(out_dir, "academic.png")
                        if 'output_path' in sig.parameters:
                            kwargs['output_path'] = academic_out
                        
                        plt.savefig = lambda fname, *args, **kw: original_savefig(academic_out, *args, **kw)
                        func(**kwargs)
                    except Exception as e:
                        print(f"  [ERROR] {name}(academic): {e}")
                        traceback.print_exc()
                    finally:
                        plt.savefig = original_savefig

                    # commercial
                    try:
                        print(f"  Executing {name} (commercial) iteration {i+1}/10...")
                        apply_commercial_style()
                        kwargs = {}
                        if 'style' in sig.parameters:
                            kwargs['style'] = 'commercial'
                        elif 'style_name' in sig.parameters:
                            kwargs['style_name'] = 'commercial'
                            
                        commercial_out = os.path.join(out_dir, "commercial.png")
                        if 'output_path' in sig.parameters:
                            kwargs['output_path'] = commercial_out
                        
                        plt.savefig = lambda fname, *args, **kw: original_savefig(commercial_out, *args, **kw)
                        func(**kwargs)
                    except Exception as e:
                        print(f"  [ERROR] {name}(commercial): {e}")
                        traceback.print_exc()
                    finally:
                        plt.savefig = original_savefig
                    
                    # Copy source code and write info.md
                    shutil.copy(file, os.path.join(out_dir, "source_code.py"))
                    info_content = f"# {name}\n\n" \
                                   f"- **Module**: `{module_name}`\n" \
                                   f"- **Function**: `{name}`\n" \
                                   f"- **Iteration**: `{i+1}/10`\n" \
                                   f"- **Generated at**: `{timestamp}`\n\n" \
                                   f"This directory contains the academic and commercial style plots generated by `{name}`."
                    with open(os.path.join(out_dir, "info.md"), "w", encoding="utf-8") as f:
                        f.write(info_content)
                        
        except Exception as e:
            print(f"[ERROR] Failed to process module {module_name}: {e}")
            traceback.print_exc()

if __name__ == "__main__":
    main()
